spring:
  datasource:
    url: jdbc:h2:file:./Desktop/db
    username: informatyka
    password: AuchAn3321
  h2.console:
    enabled: true
    path: /dlaIT/konsola
    settings.web-allow-others: true
  jpa:
    hibernate.ddl-auto: validate
  main:
    banner-mode: off