spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:h2:mem:db
    username: informatyka
    password: AuchAn3321
  h2.console:
    enabled: true
    path: /dlaIT/konsola
    settings.web-allow-others: true
  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect


